### ISSUE TITLE
不论是server.py还是server_wss.py启动后都是空白页面

### ISSUE THREAD

**Issue by RemSynch** [0x5446/api4sensevoice#5]
环境：Python3.10，torch 2.2.1CUDA11.8，torchaudio2.2.1，FFmpeg 6
通过指令启动server.py:
```
(api4sensevoice) D:\A_OtherOpenSourcePrj\api4sensevoice>python server.py --port 8888 --certfile ./certfile.pem --keyfile ./keyfile.pem
funasr version: 1.1.6.
Check update of funasr, and it would cost few times. You may disable it by set `disable_update=True` in AutoModel
You are using the latest version of funasr-1.1.6
INFO:     Started server process [24108]
INFO:     Waiting for application startup.
INFO:     Application startup complete.
INFO:     Uvicorn running on https://0.0.0.0:8888 (Press CTRL+C to quit)
```
![image](https://github.com/user-attachments/assets/3b585525-15e0-4384-a3f2-839cdc36199c)
刚开始启动时报错没有模型，我已经下载到本地后再进行启动了，启动后不报错但是依旧是空白页面
现在是完全没找到报错信息但是打不开页面
唯一一个有依赖报错信息的是Pycharm一直提示我pydantic_settings不存在，但事实是pydantic、pydantic_settings一直都存在
![image](https://github.com/user-attachments/assets/1b6ba191-e8a2-493a-8a8c-88a7b6c5f602)

**Comment by showyourlucky** [comment]
你要本地访问服务端就改成127.0.0.1:8888, 0.0.0.0:8888只是表示服务监听了8888端口

**Comment by seetimee** [comment]
这是个api,网页要通过那个html文件改端口运行
